100-hours-a-week/11-ellu-ai-summary-service

- README.md
- resolve #1 
- 개요 작성
- e888f6fadac556b1948045fd38023be07931e504 기능 설명~
- 선택사항 입니다.
> test: test

- .gitignore
- server.py
- resolve #3 
- fastapi 스켈레톤 추가
- feat: fastapi 스켈레톤 생성
- 
-
> feat: fastapi 스켈레톤 생성

- llm/wiki_chain.py
> feat:회의록 요약 기반 keywork추출(#12)

- server.py
- resolve #6
- ChromaDB 서버와의 연결 로직을 FastAPI 앱에 통합하였으며, 연결 실패 시 예외를 로깅하도록 처리했습니다.
- 아직 미완성된 LLM 모듈들과의 연결은 주석 처리하여 전체 서버 실행에 지장 없도록 구성했습니다
- server.py: chromadb.HttpClient를 통해 로컬 ChromaDB와 연결, heartbeat()를 통해 연결 확인
- 연결 실패 시 로그로 출력되도록 try-except 구문 추가
- llm/meeting_chain.py, llm/wiki_chain.py, vectordb/chroma_db.py 등 미완성 모듈 import는 주석 처리
- 선택사항 입니다.
> ✨ feat:  chroma DB 연결 (#6)

- vectordb/chroma_store.py
- resolve #7 
- 임베딩된  wiki정보의 벡터값을 ChromaDB에 저장하는 기능 구현
- 동일한 프로젝트 아이디의 기존 wiki정보는 삭제 후 최신 정보로 업데이트
> feat: wiki정보 chromaDB 저장 기능 구현(#7)

- vectordb/embed_model.py
- resolve #8 
- KoSimCSE 임베딩 모델 구현
> feat: KoSimCSE 임베딩 모델 구현(#8)

- server.py
- resolve # 18
- FastAPI 서버 초기화 및 ChromaDB 연결 상태 확인용 루트 엔드포인트 추가
- 
1e487727bd574d40ec7f16dca277cefbcfd6a9eb
- 선택사항 입니다.
> ✨ feat: FastAPI 기본 구조 설정 추가(#18)

- llm/meeting_chain.py
- resolve # 9
- 개요 작성
- [ x ] 코드가 정상적으로 컴파일되는지 확인했습니다.
- [ x ] PR이 관련 이슈를 정확히 참조하고, 적절한 라벨을 선택했습니다.
- [ x ] 모든 테스트가 성공적으로 통과했습니다.
> feat:상세일정 langchain구현(#9)

- llm/wiki_chain.py
> feat:wiki chain (#23)

- llm/wiki_retriever.py
> feat:wiki retriever (#22)

- llm/wiki_chain.py
- resolve #23 
- wiki 요약 실행
- 요약된 정보 임베딩한 벡터값과 메타데이터 ChromaDB에 저장
> feat: wiki 요약정보 임베딩 후 metadata와 함께 ChromaDB에 저장하는 기능 구현(#23)

- vectordb/chroma_db.py
> feat:chroma local db 참고용 (#27)

- config.py
- server.py
- vectordb/chroma_store.py
- resolve # 32
- 개요 작성
- 선택사항 입니다.
> refactor: 환경변수분리 (#32)

- vectordb/chroma_store.py
- resolve #34 
- embed_model import 시 폴더 경로 수정
> fix: import embed_model 파일 경로 수정(#34)

- vectordb/chroma_store.py
- resolve #37
- chroma_store 상태 반환 메세지 개선으로 새로운 프로젝트 아이디로 wiki저장 시 "wiki_saved", 같은 프로젝트 아이디로 저장 시 "wiki_updated"로 구분
> refactor: chroma_store 상태 반환 메세지 개선(#37)

- server.py
- resolve #39
- 임베딩 엔드포인트 구조 개선
> refactor: 임베딩 엔드포인트 구조 개선(#39)

- llm/meeting_chain.py
- llm/wiki_chain.py
- resolve #44 
- GPU 사용 코드 추가
- 55918752b8ce9d5caf6f5bc5a06ffab22e41408e
- 선택사항 입니다.
> feat : GPU 사용 코드 추가 (#44)

- server.py
- resolve #46 
- webhook API 구현(#46)
> feat: webhook API 구현(#46)

- llm/meeting_chain.py
- llm/wiki_chain.py
- llm/wiki_retriever.py
- server.py
- resolve #48
- task생서 api 버그 수정
- 로깅 trace 추가
- fix: task 실패시 에러 무시하는 버그 수정
- fix: 회의록 전달 후 task 생성 api 버그 수정
- chore: llm 함수 로깅 트레이스 추가
- chore: 불필요 주석 삭제
> fix: 회의록 전달 후 task 생성 api 버그 수정

- llm/meeting_chain.py
- resolve #53 
Json parsing 수정 (#53)
074a3a809805c555bd195ae6c096c8bb14e47371
- 선택사항 입니다.
> fix: Json parsing 수정 (#53)

- .github/workflows/semantic-release.yml
- resolve #5 
- semantic release 적용 
- 해당 job은 main브렌치에서만 실행됩니다
> feat: semantic-release 적용

- llm/meeting_chain.py
- server.py
- resolve # 57
- 사용자의 입력에 따른 추출이 아닌 엉뚱한 키워드로 대체되는 문제 해결
- 할루시네이션 현상 개선
- 선택사항 입니다.
> refactor: 회의록 처리 개선 및 task 프롬프트 강화 (#57)

- llm/meeting_chain.py
- resolve # 63
- 개요 작성
- 선택사항 입니다.
> fix: 대소문자 버그 수정

- .gitignore
- llm/meeting_chain.py
- llm/wiki_chain.py
- resolve #62
- meeting_chain 프롬프트 변경으로 다른 양식의 회의록 오류 수정 
- 1cc5114b71c37d1397f32c059f27589719b6237d
- 선택사항 입니다.
>  feat: gitignore 추가 및 meeting_chain 프롬프팅 수정(#62)

- .gitignore
- llm/graph.py
- llm/json_fixer.py
- llm/meeting_chain.py
- server.py
- resolve #74
- 랭그래프 구현 및 프롬프팅 수정
- 선택사항 입니다.
> refactor : 랭그래프 구현 및 프롬프팅 수정(#74)

- requirements.txt
- server.py
- resolve #76 
유저 input output DB에 저장 추가
7eed0fec6c83ffa98cb31d3b355b0c15ff731f44
> feat : 유저 input output DB에 저장 추가(#76)

- requirements.txt
- resolve # 80
- install 추가 (#80)
- 48a86ecf50a0d814c503f5de50525ce5f16c07ad
- 선택사항 입니다.
> feat : install 추가 (#80)

- llm/graph.py
- llm/meeting_chain.py
- resolve #84
- 프롬프팅 개선 및 검증 노드 추가
- 163b1f9
- 선택사항 입니다.
> feat : 프롬프팅 개선 및 검증 노드 추가(#84)

- .gitignore
- server.py
- wiki/wiki_fetcher.py
- resolve # 88
- 개요 작성
- 선택사항 입니다.
> feat: wikifetcher클래스구현(#88)

- requirements.txt
- resolve # 102
- 개요 작성
- 선택사항 입니다.
> feat:requirements수정(#102)

- llm/meeting_chain.py
- server.py
- resolve #110
위키 가져오는 부분 비활성화 및 return 양식 수정
037708378ee89f35b010e7428cc2ae2cfaac47ce
- 선택사항 입니다.
>  fix: 위키 가져오는 부분 비활성화 및 return 양식 수정(#110)

- server.py
- resolve #112
callback 함수 추가(#112)
d64a2d3d62b740b6bddc49212e41005c616c6bf0
- 선택사항 입니다.
> feat: callback 함수 추가(#112)

- app/main.py
- nodes/All_node.py
- prompts/prompt.py
- resolve #112
callback 수정
6d74517b5f44d7ecee59f261ae6df57a35eb5b79
- 선택사항 입니다.
> fix:callback 수정 (#112)

- vectordb/chroma_store.py
- resolve # 120
- 개요 작성
- 선택사항 입니다.
> 디비 저장 doc_id 변경(#120)

- nodes/graph.py
- resolve #145
- position 중복 제거
- 선택사항 입니다.
> fix : position 중복 제거

- app/main.py
logger 오류 수정
- resolve #
- 개요 작성
- 선택사항 입니다.
> stage v1.2: Update main.py

- app/config.py
- models/wiki/retriever_manager.py
- nodes/All_node.py
- resolve # 186
- 개요 작성
- 선택사항 입니다.
> feat:manager추가(#186)

- app/main.py
- schemas/main_schema.py
- resolve #187 
유저 데이터 저장
- 선택사항 입니다.
> feat: 유저 데이터 저장 part 수정(#187)

- app/config.py
- app/exceptions.py
- app/main.py
- models/stt/audio_transcriber.py
- nodes/All_node.py
- nodes/graph.py
- resolve #206 
- FastAPI `ai/audio` 엔드포인트 구현 및 예외처리(음성 파일 형식 오류, 저장 오류)하여 음성 파일 AI 서버로 받아서 임시저장
- gemini API(Gemini 2.5 Flash-Lite모델)로 음성 텍스트 변환
- 기존 task 추출 그래프 로직에 audio text 로직 추가
> 206 feature stt 기능

- app/config.py
- app/main.py
- models/stt/audio_transcriber.py
- nodes/All_node.py
- nodes/graph.py
- resolve #209 
- STT변환 결과를  /projects/{project_id}/note 엔드포인트로 반환 및 노드 삭제
> feature: STT변환 결과 엔드포인트 반환 및 노드 삭제 (#209)

- app/config.py
- nodes/graph.py
- resolve #209 
- 개요 작성
- 선택사항 입니다.
> feature: stt 변환 결과 엔드포인트로 변환(#209)

- app/main.py
> refactor: 로그 추가 (#209)

- app/main.py
- models/stt/audio_transcriber.py
- requirements.txt
- resolve #209 
- gemini api 통신 오류로 프롬프트 설정 및 오디오 바이트 변환하여 전달하도록 수정
- 내부 note 엔드포인트 호출 시 project_id 포멧 수정
> fix: gemini api 연결 오류 수정 (#209)

- models/pinecone/hybrid_retriever.py
- resolve # 215
- pine context search system 구현
- 선택사항 입니다.
> feat: pinecone subtext 검색 구현(#215)

- models/pinecone/hybrid_retriever.py
- resolve # 183
- 역할에 대한 정의 검색
- 선택사항 입니다.
> feat: 역할 검색(#183)

- prompts/prompt.py
- resolve # 220
- 프롬프트를 수정하여 subtask 반환시 context 품질을 높임
- 선택사항 입니다.
> refactor: prompt 수정(#220)

- app/config.py
- requirements.txt
- resolve # 224 
- 개요 작성
- 선택사항 입니다.
> refactor: update config and requirements(#224)

- app/main.py
- resolve #234 
- 개요 작성
- 선택사항 입니다.
> fix: suffix 수정 (#234)
